export const constants = {
  FETCH_QUIZ_BY_ID: "FETCH_QUIZ_BY_ID",
  FETCH_QUIZ_DATA: "FETCH_QUIZ_DATA",
  ADD_A_QUIZ: "ADD_A_QUIZ",
  REMOVE_A_QUIZ: "REMOVE_A_QUIZ",
  ADD_QUESTION_TYPE: "ADD_TYPE",
  ADD_QUESTION_INPUT: "ADD_QUESTION_INPUT",
  ADD_ANSWER_OPTION: "ADD_ANSWER_OPTION",
  REMOVE_ALL_OPTIONS: "REMOVE_ALL_OPTIONS",
  SET_CORRECT_ANSWER: "SET_CORRECT_ANSWER",
  REMOVE_ALL_CORRECT_ANSWERS: "REMOVE_ALL_CORRECT_ANSWERS",
  REMOVE_CORRECT_ANSWER: "REMOVE_CORRECT_ANSWER",
  REMOVE_OPTION: "REMOVE_OPTION"
};
